<a href="https://colab.research.google.com/github/Ajay-Sai-Kiran/Machine_learning_challenge/blob/main/AdaBoost.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Implementation of ADAboost

In [ ]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from sklearn.ensemble import AdaBoostClassifier

# Create the model with 100 trees
model = AdaBoostClassifier(base_estimator=None,n_estimators=50, learning_rate=1.0, algorithm='SAMME.R', random_state=None)

In [ ]:
df=pd.read_csv("/content/Train (2).csv")

In [ ]:
df.head()

ID  Gender Ever_Married  ...  Family_Size  Var_1 Segmentation
0  462809    Male           No  ...          4.0  Cat_4            D
1  462643  Female          Yes  ...          3.0  Cat_4            A
2  466315  Female          Yes  ...          1.0  Cat_6            B
3  461735    Male          Yes  ...          2.0  Cat_6            B
4  462669  Female          Yes  ...          6.0  Cat_6            A

[5 rows x 11 columns]

In [ ]:
df.shape

(8068, 11)

In [ ]:
df.columns

Index(['ID', 'Gender', 'Ever_Married', 'Age', 'Graduated', 'Profession',
       'Work_Experience', 'Spending_Score', 'Family_Size', 'Var_1',
       'Segmentation'],
      dtype='object')

In [ ]:
df.drop(['ID'], axis=1)

Gender Ever_Married  Age  ... Family_Size  Var_1  Segmentation
0       Male           No   22  ...         4.0  Cat_4             D
1     Female          Yes   38  ...         3.0  Cat_4             A
2     Female          Yes   67  ...         1.0  Cat_6             B
3       Male          Yes   67  ...         2.0  Cat_6             B
4     Female          Yes   40  ...         6.0  Cat_6             A
...      ...          ...  ...  ...         ...    ...           ...
8063    Male           No   22  ...         7.0  Cat_1             D
8064    Male           No   35  ...         4.0  Cat_4             D
8065  Female           No   33  ...         1.0  Cat_6             D
8066  Female           No   27  ...         4.0  Cat_6             B
8067    Male          Yes   37  ...         3.0  Cat_4             B

[8068 rows x 10 columns]

In [ ]:
df['Segmentation'].value_counts()

D    2268
A    1972
C    1970
B    1858
Name: Segmentation, dtype: int64

In [ ]:
df.isnull().sum()

ID                   0
Gender               0
Ever_Married       140
Age                  0
Graduated           78
Profession         124
Work_Experience    829
Spending_Score       0
Family_Size        335
Var_1               76
Segmentation         0
dtype: int64

In [ ]:
df.isnull().sum()

ID                   0
Gender               0
Ever_Married       140
Age                  0
Graduated           78
Profession         124
Work_Experience    829
Spending_Score       0
Family_Size        335
Var_1               76
Segmentation         0
dtype: int64

In [ ]:
df.dtypes

ID                   int64
Gender              object
Ever_Married        object
Age                  int64
Graduated           object
Profession          object
Work_Experience    float64
Spending_Score      object
Family_Size        float64
Var_1               object
Segmentation        object
dtype: object

In [ ]:
categorical_features = df.select_dtypes(include=[np.object]).columns
print("total categorical_features",len(categorical_features))

total categorical_features 7


In [ ]:
df['Spending_Score'].value_counts()

Low        4878
Average    1974
High       1216
Name: Spending_Score, dtype: int64

In [ ]:
df['Profession'].value_counts()

Artist           2516
Healthcare       1332
Entertainment     949
Engineer          699
Doctor            688
Lawyer            623
Executive         599
Marketing         292
Homemaker         246
Name: Profession, dtype: int64

In [ ]:
df['Var_1'].value_counts()

Cat_6    5238
Cat_4    1089
Cat_3     822
Cat_2     422
Cat_7     203
Cat_1     133
Cat_5      85
Name: Var_1, dtype: int64

In [ ]:
df['Family_Size'].value_counts()

2.0    2390
3.0    1497
1.0    1453
4.0    1379
5.0     612
6.0     212
7.0      96
8.0      50
9.0      44
Name: Family_Size, dtype: int64

#Encoding Categorical Data

In [ ]:
# Replacing Male with 0 and Female with 1 in Gender column
df['Gender'] = df['Gender'].replace({'Male':0,'Female':1})

In [ ]:
# Replacing No with 0 and Yes with 1 in Ever_Married column
df['Ever_Married'] = df['Ever_Married'].replace({'No':0,'Yes':1})

In [ ]:
# Replacing No with 0 and Yes with 1 in Graduated column
df['Graduated'] = df['Graduated'].replace({'No':0,'Yes':1})

In [ ]:
# Replacing Low with 0, Average with 1 and High with 2 in Spending_Score column
df['Spending_Score'] = df['Spending_Score'].replace({'Low':0,'Average':1,'High':2})

In [ ]:
# Replacing Cat_1 with 1, Cat_2 with 2, Cat_3 with 3, Cat4 with 4, Cat_5 with 5, Cat_6 with 6, and Cat_7 with 7 in Var_1 column
df['Var_1'] = df['Var_1'].replace({'Cat_1':1,'Cat_2':2,'Cat_3':3,'Cat_4':4,'Cat_5':5,'Cat_6':6,'Cat_7':7})

In [ ]:
# Replacing Artist with 0, Healthcare with 1, Entertainment with 2, Engineer with 3, Doctor with 4, Lawyer with 5, Executive with 6, Marketing with 7 and Homemaker with 8 in Var_1 column
df['Profession'] = df['Profession'].replace({'Artist':0,'Healthcare':1,'Entertainment':2,'Engineer':3,'Doctor':4,'Lawyer':5,'Executive':6,'Marketing':7,'Homemaker':8})

In [ ]:
# Replacing A with 0, B with 1, C with 2 and D with 3 in Spending_Score column
df['Segmentation'] = df['Segmentation'].replace({'A':0,'B':1,'C':2,'D':3})

In [ ]:
df

ID  Gender  Ever_Married  ...  Family_Size  Var_1  Segmentation
0     462809       0           0.0  ...          4.0    4.0             3
1     462643       1           1.0  ...          3.0    4.0             0
2     466315       1           1.0  ...          1.0    6.0             1
3     461735       0           1.0  ...          2.0    6.0             1
4     462669       1           1.0  ...          6.0    6.0             0
...      ...     ...           ...  ...          ...    ...           ...
8063  464018       0           0.0  ...          7.0    1.0             3
8064  464685       0           0.0  ...          4.0    4.0             3
8065  465406       1           0.0  ...          1.0    6.0             3
8066  467299       1           0.0  ...          4.0    6.0             1
8067  461879       0           1.0  ...          3.0    4.0             1

[8068 rows x 11 columns]

#Filling missing data

In [ ]:
df.isnull().sum()

ID                   0
Gender               0
Ever_Married       140
Age                  0
Graduated           78
Profession         124
Work_Experience    829
Spending_Score       0
Family_Size        335
Var_1               76
Segmentation         0
dtype: int64

In [ ]:
df['Ever_Married'].fillna(int(df['Ever_Married'].mean()), inplace=True)

In [ ]:
df['Ever_Married'].value_counts()

1.0    4643
0.0    3425
Name: Ever_Married, dtype: int64

In [ ]:
df['Graduated'].fillna(int(df['Graduated'].mean()), inplace=True)
df['Profession'].fillna(int(df['Profession'].mean()), inplace=True)
df['Work_Experience'].fillna(int(df['Work_Experience'].mean()), inplace=True)
df['Family_Size'].fillna(int(df['Family_Size'].mean()), inplace=True)
df['Var_1'].fillna(int(df['Var_1'].mean()), inplace=True)

In [ ]:
df.isna().sum()

ID                 0
Gender             0
Ever_Married       0
Age                0
Graduated          0
Profession         0
Work_Experience    0
Spending_Score     0
Family_Size        0
Var_1              0
Segmentation       0
dtype: int64

#Splitting the data

In [ ]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:

model.fit(X_train, y_train)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=1.0,
                   n_estimators=50, random_state=None)

In [ ]:
y_pred = model.predict(X_test)


In [ ]:
df = pd.DataFrame({'Actual': y_test.flatten(), 'Predicted': y_pred.flatten()})
df

Actual  Predicted
0          3          3
1          0          2
2          3          3
3          2          2
4          3          3
...      ...        ...
1609       0          0
1610       1          0
1611       0          2
1612       0          3
1613       3          3

[1614 rows x 2 columns]

In [ ]:
#Evaluation Metrics

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[170  72  62  87]
 [105 119 109  36]
 [ 45  94 197  44]
 [ 81  31  19 343]]


0.5136307311028501